# Generated by Django 5.0.4 on 2024-05-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payapp", "0003_transaction_currency_paymentrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="inward_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="outward_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
